// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type PdfMetadatum struct {
	ID        uuid.UUID
	CreatedAt time.Time
	FilePath  string
	GroupID   uuid.NullUUID
}
