// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pdf_queries.sql

package database

import (
	"context"
)

const testMetadata = `-- name: TestMetadata :many
select id, created_at, file_path, group_id from pdf_metadata
`

func (q *Queries) TestMetadata(ctx context.Context) ([]PdfMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, testMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PdfMetadatum
	for rows.Next() {
		var i PdfMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.FilePath,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
